### ISSUE TITLE
small changes in  app.component.html 

### ISSUE THREAD

**Issue by nireekshshetty** [PallaviKatari/AngularProject#1]
The code in the app.component.html file must be changed to this

`<app-nav></app-nav>
<app-carousel></app-carousel>
<router-outlet></router-outlet>
<app-footer></app-footer>`

because we keep footer at the bottom..
In the present code router-outlet is called after footer which makes footer appear before any component that is routed

I found this while trying in my device

**Comment by PallaviKatari** [comment]
.
